/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package alugueldepatins;

import javax.swing.JOptionPane;

public class JanelaDevolucao extends javax.swing.JDialog {
    private ModeloTabelaAluguel modeloAluguel;
    private ControladorAluguel controladorAluguel;
    private ControladorPagamento controladorPagamento;
    
    public JanelaDevolucao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modeloAluguel = new ModeloTabelaAluguel();
        tabAlugueis.setModel(modeloAluguel);
        //controladorAluguel = new ControladorAluguel();
    }
    
    //ultima alteração; controladorPagamento
    public void addControladorAluguel(ControladorAluguel controladorAluguel, ModeloTabelaAluguel modeloAluguel, ControladorPagamento controladorPagamento){
        this.controladorAluguel = controladorAluguel;
        //this.modeloAluguel = modeloAluguel;
        this.controladorPagamento = controladorPagamento;
    }
    
    /*public void addTabelaAluguel(Aluguel aluguel){
        controladorAluguel.incluirAluguel(aluguel);
        modeloAluguel.incluirAluguel(aluguel);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edIdAluguel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edHoraFim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edDanificado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edPrecoAdicional = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edFormaPagamento = new javax.swing.JTextField();
        buConfirmarDevolucao = new javax.swing.JButton();
        buCancelarDevolucao = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        laValorTotalAluguel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabAlugueis = new javax.swing.JTable();
        buCalcularValorTotal = new javax.swing.JButton();
        buBuscarAluguel = new javax.swing.JButton();
        buMostrarAlugueis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Devolução de Patins");

        jLabel2.setText("ID Aluguel");

        jLabel3.setText("Hora Fim");

        jLabel4.setText("Danificado? (true or false)");

        jLabel5.setText("Preço adicional(caso danificado)");

        jLabel6.setText("Forma de Pagamento");

        buConfirmarDevolucao.setText("Confirmar devolução");
        buConfirmarDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buConfirmarDevolucaoActionPerformed(evt);
            }
        });

        buCancelarDevolucao.setText("Cancelar devolução");
        buCancelarDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCancelarDevolucaoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Valor Total do Aluguel:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("R$");

        laValorTotalAluguel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        laValorTotalAluguel.setText("0");

        jScrollPane1.setViewportView(tabAlugueis);

        buCalcularValorTotal.setText("Calcular Valor Total do Aluguel");
        buCalcularValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCalcularValorTotalActionPerformed(evt);
            }
        });

        buBuscarAluguel.setText("Buscar Aluguel");
        buBuscarAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buBuscarAluguelActionPerformed(evt);
            }
        });

        buMostrarAlugueis.setText("Mostrar  Alugueis");
        buMostrarAlugueis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buMostrarAlugueisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laValorTotalAluguel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buConfirmarDevolucao)
                        .addGap(18, 18, 18)
                        .addComponent(buCancelarDevolucao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(edFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(edPrecoAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edIdAluguel)
                                    .addComponent(edHoraFim, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(buBuscarAluguel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buMostrarAlugueis))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(edDanificado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buCalcularValorTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edIdAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buBuscarAluguel)
                    .addComponent(buMostrarAlugueis))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edDanificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edPrecoAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(edFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buCalcularValorTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(laValorTotalAluguel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buConfirmarDevolucao)
                    .addComponent(buCancelarDevolucao))
                .addGap(24, 24, 24))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buBuscarAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buBuscarAluguelActionPerformed
        if(edIdAluguel.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Erro! Campo de busca vazio!", "Informações do Patins", JOptionPane.INFORMATION_MESSAGE);           
        } else{
            int id = Integer.parseInt(edIdAluguel.getText());
            Aluguel aluguel = controladorAluguel.selecionarAluguelPorId(id);

            if(aluguel != null){
                System.out.println("Aluguel existe!");
                JOptionPane.showMessageDialog(null, aluguel.retornaAluguel(), "Informações do Patins", JOptionPane.INFORMATION_MESSAGE);
            } else{
                System.out.println("Aluguel não existe!");
                JOptionPane.showMessageDialog(null, "Não existe esse aluguel, confira o Id!", "Informações do Patins", JOptionPane.INFORMATION_MESSAGE);            
            }
        }
    }//GEN-LAST:event_buBuscarAluguelActionPerformed

    private void buCalcularValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCalcularValorTotalActionPerformed
        int id = Integer.parseInt(edIdAluguel.getText());
        Aluguel aluguel = controladorAluguel.selecionarAluguelPorId(id);
        
        Patins patins = aluguel.obterPatins();
        boolean danificado = Boolean.parseBoolean(edDanificado.getText());
        float precoAdicional;
        float precoPatins = patins.obterPreco();
        float precoTotal;
        System.out.println(String.format("Preco do Patins %.2f",precoPatins));
        
        if (danificado == true){
            precoAdicional = Float.parseFloat(edPrecoAdicional.getText());
            System.out.println(String.format("Taxa de dano %.2f",precoAdicional));
            precoTotal = precoAdicional + precoPatins;
        } else{
            precoTotal = precoPatins;
        }
        System.out.println(String.format("Preco Final do Patins %.2f",precoTotal));
        laValorTotalAluguel.setText(String.format("%.2f", precoTotal));
    }//GEN-LAST:event_buCalcularValorTotalActionPerformed

    private void buCancelarDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCancelarDevolucaoActionPerformed
        dispose();
    }//GEN-LAST:event_buCancelarDevolucaoActionPerformed

    private void buConfirmarDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buConfirmarDevolucaoActionPerformed
        Devolucao devolucao = new Devolucao();
        Pagamento pagamento = new Pagamento();
        
        int idAluguel = Integer.parseInt(edIdAluguel.getText());
        
        //adicionado para verificar se tem patins
        Aluguel aluguel = controladorAluguel.selecionarAluguelPorId(idAluguel);
        Patins patins = aluguel.obterPatins();
        
        if(aluguel != null){
            devolucao.alterarAluguel(aluguel);
            devolucao.alterarHoraFim(edHoraFim.getText());
            devolucao.alterarDanificado(Boolean.parseBoolean(edDanificado.getText()));
            if(!edPrecoAdicional.getText().isEmpty() || Boolean.parseBoolean(edDanificado.getText()) == true){
                devolucao.alterarPrecoAdicionalDano(Float.parseFloat(edPrecoAdicional.getText()));
            } else{
                devolucao.alterarPrecoAdicionalDano(0);
            }
            devolucao.alterarValorAluguel(patins.obterPreco());
            devolucao.alterarFormaPagamento(edFormaPagamento.getText());
            devolucao.alterarStatusDevolucao(true);
                        
            pagamento.alterarIdPagamento(controladorPagamento.obterTamanhoPagamento() + 1);
            pagamento.alterarDevolucao(devolucao);
            if(!edPrecoAdicional.getText().isEmpty() || Boolean.parseBoolean(edDanificado.getText()) == true){
                pagamento.alterarValorPagamento(Float.parseFloat(edPrecoAdicional.getText()) + patins.obterPreco());
            } else{
                pagamento.alterarValorPagamento(patins.obterPreco());                
            }
            pagamento.alterarFormaPagamento(edFormaPagamento.getText());
            
            controladorPagamento.incluirPagamento(pagamento);
            controladorAluguel.excluirAluguel(aluguel);
            System.out.println("Devolucao e Pagamento Adicionado a Lista!");
            System.out.println(controladorPagamento.obterPagamentos());
            
            JOptionPane.showMessageDialog(null, "Devolução realizada com sucesso!", "Informações da Devolução", JOptionPane.INFORMATION_MESSAGE);
           
        } else{
            JOptionPane.showMessageDialog(null, "Erro ao fazer a Devolucao! Confira o Id!", "Aviso da Devolução", JOptionPane.INFORMATION_MESSAGE);
        }
        
        limparCamposDevolucao();
    }//GEN-LAST:event_buConfirmarDevolucaoActionPerformed

    private void buMostrarAlugueisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buMostrarAlugueisActionPerformed
        int idAluguel;
        String itemAluguel;
        String mensagemAluguel = "";
        
        for (int i = 0; i < controladorAluguel.obterTamanho(); i++){
            idAluguel = i + 1;
            Aluguel aluguel = controladorAluguel.selecionarAluguelPorId(idAluguel);
            
            if(aluguel != null){
                itemAluguel = aluguel.retornaAluguel();
                mensagemAluguel = mensagemAluguel + itemAluguel + "\n\n";
            } 
        }
        if(mensagemAluguel.equals("")){
            JOptionPane.showMessageDialog(null, "Não há alugueis em andamento!", "Alugueis em andamento", JOptionPane.INFORMATION_MESSAGE);         
        } else{
            JOptionPane.showMessageDialog(null, mensagemAluguel, "Alugueis em andamento", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buMostrarAlugueisActionPerformed
    
    public void limparCamposDevolucao(){
        edIdAluguel.setText("");
        edHoraFim.setText("");
        edDanificado.setText("");
        edPrecoAdicional.setText("");
        edFormaPagamento.setText("");
        laValorTotalAluguel.setText("0");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaDevolucao dialog = new JanelaDevolucao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buBuscarAluguel;
    private javax.swing.JButton buCalcularValorTotal;
    private javax.swing.JButton buCancelarDevolucao;
    private javax.swing.JButton buConfirmarDevolucao;
    private javax.swing.JButton buMostrarAlugueis;
    private javax.swing.JTextField edDanificado;
    private javax.swing.JTextField edFormaPagamento;
    private javax.swing.JTextField edHoraFim;
    private javax.swing.JTextField edIdAluguel;
    private javax.swing.JTextField edPrecoAdicional;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel laValorTotalAluguel;
    private javax.swing.JTable tabAlugueis;
    // End of variables declaration//GEN-END:variables
}
