package alugueldepatins;

import javax.swing.JOptionPane;

public class JanelaAluguel extends javax.swing.JDialog {
    private ModeloTabelaPatins modeloPatins;
    private ControladorPatins controladorPatins;
    private ControladorAluguel controladorAluguel;
    private ModeloTabelaAluguel modeloAluguel;
    Patins patins1;
    Patins patins2;
    Patins patins3;
    
    public JanelaAluguel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modeloPatins = new ModeloTabelaPatins();
        tabPatins.setModel(modeloPatins);
        controladorPatins = new ControladorPatins();
    }
    
    public void addControladorAluguel(ControladorAluguel controladorAluguel, ModeloTabelaAluguel modeloAluguel){
        this.controladorAluguel = controladorAluguel;
        //this.modeloAluguel = modeloAluguel;
    }
    
    public void inicializarTabelaPatins(){
        patins1 = new Patins();
        patins1.alterarIdPatins(1);
        patins1.alterarNumeroPe(40);
        patins1.alterarQuantidadeDisponivel(1);
        patins1.alterarPreco(20);
        patins1.alterarStatusDisponivel(true);
        controladorPatins.incluirPatins(patins1);
        modeloPatins.incluirPatins(patins1);
        
        patins2 = new Patins();
        patins2.alterarIdPatins(2);
        patins2.alterarNumeroPe(37);
        patins2.alterarQuantidadeDisponivel(1);
        patins2.alterarPreco(15);
        patins2.alterarStatusDisponivel(true);
        controladorPatins.incluirPatins(patins2);
        modeloPatins.incluirPatins(patins2);
        
        patins3 = new Patins();
        patins3.alterarIdPatins(3);
        patins3.alterarNumeroPe(44);
        patins3.alterarQuantidadeDisponivel(1);
        patins3.alterarPreco(30);
        patins3.alterarStatusDisponivel(true);
        controladorPatins.incluirPatins(patins3);
        modeloPatins.incluirPatins(patins3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPatins = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        edIdPatins = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edCPFCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edNumeroPe = new javax.swing.JTextField();
        buCancelarAluguel = new javax.swing.JButton();
        buBuscarPatins = new javax.swing.JButton();
        buConfirmarAluguel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        edHoraInicio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(tabPatins);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Alugar Patins");

        jLabel2.setText("ID Patins");

        jLabel3.setText("CPF Cliente");

        jLabel4.setText("Numero do Pe");

        buCancelarAluguel.setText("Cancelar Aluguel");
        buCancelarAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCancelarAluguelActionPerformed(evt);
            }
        });

        buBuscarPatins.setText("Buscar Patins");
        buBuscarPatins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buBuscarPatinsActionPerformed(evt);
            }
        });

        buConfirmarAluguel.setText("Confirmar Aluguel");
        buConfirmarAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buConfirmarAluguelActionPerformed(evt);
            }
        });

        jLabel5.setText("Hora Inicio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edIdPatins, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(edCPFCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edNumeroPe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edHoraInicio, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(63, 63, 63))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(buCancelarAluguel)
                            .addComponent(buConfirmarAluguel)
                            .addComponent(jLabel5)
                            .addComponent(buBuscarPatins))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edIdPatins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edNumeroPe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(buBuscarPatins)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buConfirmarAluguel)
                .addGap(18, 18, 18)
                .addComponent(buCancelarAluguel)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buBuscarPatinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buBuscarPatinsActionPerformed
        int id = Integer.parseInt(edIdPatins.getText());
        Patins patins = controladorPatins.selecionarPatinsPorId(id);
        
        /*Adicionado o JOptionPane para exibição de mensagem*/
        if(patins != null){
            System.out.println("Patins existe!");
            JOptionPane.showMessageDialog(null, patins.retornaPatins(), "Informações do Patins", JOptionPane.INFORMATION_MESSAGE);
        } else{
            System.out.println("Patins nao existe!");
            JOptionPane.showMessageDialog(null, "Não existe patins com esse ID!", "Informações do Patins", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_buBuscarPatinsActionPerformed

    private void buConfirmarAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buConfirmarAluguelActionPerformed
        //controladorAluguel = new ControladorAluguel();
        Aluguel aluguel = new Aluguel();
        Cliente cliente = new Cliente();
        int idPatins = Integer.parseInt(edIdPatins.getText());
        
        //adicionado para verificar se tem patins
        Patins patins = controladorPatins.selecionarPatinsPorId(idPatins); 
        
        //adicionado para add apenas se existir patins
        if(patins != null){
            cliente.alterarCpf(edCPFCliente.getText());
            cliente.alterarNumeroPeCliente(Integer.parseInt(edNumeroPe.getText()));

            aluguel.alterarIdAluguel(controladorAluguel.obterTamanho()); //calcular a id
            aluguel.alterarCliente(cliente);
            aluguel.alterarPatins(controladorPatins.selecionarPatinsPorId(idPatins));
            aluguel.alterarHoraInicio(edHoraInicio.getText());


            controladorAluguel.incluirAluguel(aluguel);
            System.out.println("Aluguel Adicionado a Lista!");
            System.out.println(controladorAluguel.obterAluguel());
            //modeloAluguel.incluirAluguel(aluguel);
            //adicionado para exibir mensagem
            JOptionPane.showMessageDialog(null, "Aluguel realizado com sucesso!", "Informações do Aluguel", JOptionPane.INFORMATION_MESSAGE);
            
        } else{
            JOptionPane.showMessageDialog(null, "Erro ao fazer aluguel! Confira o ID!", "Aviso do Aluguel", JOptionPane.INFORMATION_MESSAGE);
        }
        
        limparCamposAluguel();
    }//GEN-LAST:event_buConfirmarAluguelActionPerformed

    private void buCancelarAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCancelarAluguelActionPerformed
        dispose();
    }//GEN-LAST:event_buCancelarAluguelActionPerformed
    
    private void limparCamposAluguel(){
        edIdPatins.setText("");
        edCPFCliente.setText("");
        edNumeroPe.setText("");
        edHoraInicio.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaAluguel dialog = new JanelaAluguel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buBuscarPatins;
    private javax.swing.JButton buCancelarAluguel;
    private javax.swing.JButton buConfirmarAluguel;
    private javax.swing.JTextField edCPFCliente;
    private javax.swing.JTextField edHoraInicio;
    private javax.swing.JTextField edIdPatins;
    private javax.swing.JTextField edNumeroPe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabPatins;
    // End of variables declaration//GEN-END:variables
}
