package alugueldepatins;

import javax.swing.JOptionPane;

public class JanelaFechamentoCaixa extends javax.swing.JDialog {
    private ControladorPagamento controladorPagamento;
    
    public JanelaFechamentoCaixa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void addControladorPagamento(ControladorPagamento controladorPagamento){
        this.controladorPagamento = controladorPagamento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buCalcularSomaCaixa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        laValorTotalCaixa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buEnviar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        edSomaFicha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        buCancelarFechamento = new javax.swing.JButton();
        buExibirPagamentos = new javax.swing.JButton();
        buExibirValoresPorMetodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Fechamento do Caixa");

        buCalcularSomaCaixa.setText("Calcular soma do caixa");
        buCalcularSomaCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCalcularSomaCaixaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Valor Total Caixa");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("R$");

        laValorTotalCaixa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        laValorTotalCaixa.setText("0");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Valor da Soma da Ficha");

        buEnviar.setText("Enviar");
        buEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buEnviarActionPerformed(evt);
            }
        });

        jLabel5.setText("Clique no botão \"enviar\" para enviar o total arrecadado na soma do caixa e das fichas.");

        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText("Ao clicar, o caixa será fechado!");

        buCancelarFechamento.setText("Cancelar Fechamento do Caixa");
        buCancelarFechamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCancelarFechamentoActionPerformed(evt);
            }
        });

        buExibirPagamentos.setText("Exibir todos os pagamentos");
        buExibirPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buExibirPagamentosActionPerformed(evt);
            }
        });

        buExibirValoresPorMetodo.setText("Valores obtidos por método");
        buExibirValoresPorMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buExibirValoresPorMetodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buCalcularSomaCaixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buExibirValoresPorMetodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buExibirPagamentos)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(edSomaFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(laValorTotalCaixa))
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buEnviar)
                                .addGap(38, 38, 38)
                                .addComponent(buCancelarFechamento))
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(45, 45, 45)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buCalcularSomaCaixa)
                    .addComponent(buExibirPagamentos)
                    .addComponent(buExibirValoresPorMetodo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(laValorTotalCaixa))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edSomaFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buEnviar)
                    .addComponent(buCancelarFechamento))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buCalcularSomaCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCalcularSomaCaixaActionPerformed
        int idPagamento;
        float somaValoresPagamento = 0;
        
        for (int i = 0; i < controladorPagamento.obterTamanhoPagamento(); i++){
            idPagamento = i + 1;
            Pagamento pagamento = controladorPagamento.selecionarPagamentoPorId(idPagamento);
            
            somaValoresPagamento = somaValoresPagamento + pagamento.obterValorPagamento();
        }
        
        laValorTotalCaixa.setText(String.format("%.2f", somaValoresPagamento));
    }//GEN-LAST:event_buCalcularSomaCaixaActionPerformed

    private void buExibirPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buExibirPagamentosActionPerformed
        int idPagamento;
        String itemPagamento;
        String mensagemPagamento = "";
        
        for (int i = 0; i < controladorPagamento.obterTamanhoPagamento(); i++){
            idPagamento = i + 1;
            Pagamento pagamento = controladorPagamento.selecionarPagamentoPorId(idPagamento);
            
            itemPagamento = pagamento.retornaPagamento();
            mensagemPagamento = mensagemPagamento + itemPagamento + "\n\n";
        }
        if(mensagemPagamento.equals("")){
            JOptionPane.showMessageDialog(null, "Não foram efetuados pagamentos!", "Histórico de Pagamentos", JOptionPane.INFORMATION_MESSAGE);         
        } else{
            JOptionPane.showMessageDialog(null, mensagemPagamento, "Histórico de Pagamentos", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buExibirPagamentosActionPerformed

    private void buExibirValoresPorMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buExibirValoresPorMetodoActionPerformed
        int idPagamento;
        float valorTotalPix = 0;
        String mensagemPix = "Total realizado por Pix: R$";
        float valorTotalDinheiro = 0;
        String mensagemDinheiro = "Total realizado por dinheiro: R$";
        float valorTotalCartao = 0;
        String mensagemCartao = "Total realizado por cartão: R$";
        float valorTotalOutros = 0;
        String mensagemOutros = "Total realizado por outros métodos: R$";
        
        for (int i = 0; i < controladorPagamento.obterTamanhoPagamento(); i++){
            idPagamento = i + 1;
            Pagamento pagamento = controladorPagamento.selecionarPagamentoPorId(idPagamento);
            
            switch (pagamento.obterFormaPagamento()) {
                case "Pix":
                    valorTotalPix = valorTotalPix + pagamento.obterValorPagamento();
                    break;
                case "Dinheiro":
                    valorTotalDinheiro = valorTotalDinheiro + pagamento.obterValorPagamento();
                    break;
                case "Cartão":
                    valorTotalCartao = valorTotalCartao + pagamento.obterValorPagamento();
                    break;
                default:
                    valorTotalOutros = valorTotalOutros + pagamento.obterValorPagamento();
                    break;
            }
        }
        
        String mensagemValores = mensagemPix + valorTotalPix +"\n" +
                mensagemDinheiro + valorTotalDinheiro+ "\n" +
                mensagemCartao + valorTotalCartao +"\n" +
                mensagemOutros + valorTotalOutros;
              
        JOptionPane.showMessageDialog(null, mensagemValores, "Valores obtidos por método de pagamento", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_buExibirValoresPorMetodoActionPerformed

    private void buCancelarFechamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCancelarFechamentoActionPerformed
        dispose();
    }//GEN-LAST:event_buCancelarFechamentoActionPerformed

    private void buEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buEnviarActionPerformed
        if (edSomaFicha.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo de Soma da Ficha!", "Aviso!", JOptionPane.INFORMATION_MESSAGE);   
        } else{        
            JOptionPane.showMessageDialog(null, "Dia finalizado! \nTodos os dados obtidos foram enviados ao nosso banco de dados e para o gerente. \nAté o próximo dia!", "Finalização do dia", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_buEnviarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaFechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaFechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaFechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaFechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaFechamentoCaixa dialog = new JanelaFechamentoCaixa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buCalcularSomaCaixa;
    private javax.swing.JButton buCancelarFechamento;
    private javax.swing.JButton buEnviar;
    private javax.swing.JButton buExibirPagamentos;
    private javax.swing.JButton buExibirValoresPorMetodo;
    private javax.swing.JTextField edSomaFicha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel laValorTotalCaixa;
    // End of variables declaration//GEN-END:variables
}
